// Seeder para usuarios mínimos
'use strict';
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const now = new Date();
    const users = [
      {id:'EQP-BD2B4',inventory_number:'SBS-0003',type:'desktop',assigned_user_id:'44782',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515618',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-F62D7',inventory_number:'SBS-0004',type:'desktop',assigned_user_id:'43179',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515619',status:'Activo',location:'UNIDAD IGUALDAD DE GENERO',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-EF637',inventory_number:'SBS-0005',type:'desktop',assigned_user_id:'45253',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  500 GB Mecanico.',serial_number:'1561515620',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-72397',inventory_number:'SBS-0006',type:'desktop',assigned_user_id:'47700',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  500 GB Mecanico.',serial_number:'1561515621',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-9234C',inventory_number:'SBS-0007',type:'desktop',assigned_user_id:'42950',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515623',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-C0E1D',inventory_number:'SBS-0008',type:'desktop',assigned_user_id:'80705',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515624',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-37569',inventory_number:'SBS-0009',type:'desktop',assigned_user_id:'28125',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro Mecanico 320 gb ',serial_number:'1561515625',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'Falla Monitor',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-A304C',inventory_number:'SBS-0010',type:'desktop',assigned_user_id:'31244',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515626',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-84708',inventory_number:'SBS-0011',type:'desktop',assigned_user_id:'45732',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515627',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-332EB',inventory_number:'SBS-0012',type:'desktop',assigned_user_id:'80895',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515628',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-CB500',inventory_number:'SBS-0013',type:'desktop',assigned_user_id:'83199',brand:'Dell',model:'Inspire',processor:' Procesador RYZEN 5 5600',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515629',status:'Activo',location:'ORGANO INTERNO DE CONTROL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-48808',inventory_number:'SBS-0014',type:'desktop',assigned_user_id:'41965',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515630',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-38E30',inventory_number:'SBS-0015',type:'desktop',assigned_user_id:'48033',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515631',status:'Activo',location:'SUBSECRETARIA DE INCLUSION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-14B53',inventory_number:'SBS-0016',type:'desktop',assigned_user_id:'43702',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515632',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-3E31E',inventory_number:'SBS-0017',type:'desktop',assigned_user_id:'39951',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 3 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515633',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-2558D',inventory_number:'SBS-0018',type:'desktop',assigned_user_id:'42946',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515634',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-847AF',inventory_number:'SBS-0019',type:'desktop',assigned_user_id:'43257',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515635',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-A4BBA',inventory_number:'SBS-0020',type:'desktop',assigned_user_id:'47701',brand:'Dell',model:'Inspire',processor:' Procesador E5500',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515636',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-C59EA',inventory_number:'SBS-0021',type:'desktop',assigned_user_id:'81788',brand:'Dell',model:'Inspire',processor:' Procesador J1900 ',ram:' 8 Gb de Ram ',hard_drive:' Disco Solido de 240GB',serial_number:'1561515637',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-83B2F',inventory_number:'SBS-0022',type:'desktop',assigned_user_id:'47753',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  1TB GB Mecanico.',serial_number:'1561515638',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-07764',inventory_number:'SBS-0023',type:'desktop',assigned_user_id:'30289',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515639',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-416A1',inventory_number:'SBS-0024',type:'desktop',assigned_user_id:'47811',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515640',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5199D',inventory_number:'SBS-0025',type:'desktop',assigned_user_id:'42637',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515641',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-87E0E',inventory_number:'SBS-0026',type:'desktop',assigned_user_id:'32982',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515642',status:'Activo',location:'OFICIALIA DE PARTES',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-01373',inventory_number:'SBS-0027',type:'desktop',assigned_user_id:'20822',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 2 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515643',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-56B64',inventory_number:'SBS-0028',type:'desktop',assigned_user_id:'81632',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515644',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-60CCD',inventory_number:'SBS-0029',type:'desktop',assigned_user_id:'82348',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515645',status:'Activo',location:'SUBSECRETARIA DE INCLUSION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-3A8B7',inventory_number:'SBS-0030',type:'desktop',assigned_user_id:'43126',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515646',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-F8FA4',inventory_number:'SBS-0031',type:'desktop',assigned_user_id:'48234',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515647',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-911C3',inventory_number:'SBS-0032',type:'desktop',assigned_user_id:'48029',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515648',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'VEHICULOS',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-6A43E',inventory_number:'SBS-0033',type:'desktop',assigned_user_id:'44569',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515649',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-E99CC',inventory_number:'SBS-0034',type:'desktop',assigned_user_id:'46910',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515650',status:'Activo',location:'ORGANO INTERNO DE CONTROL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-F0937',inventory_number:'SBS-0035',type:'desktop',assigned_user_id:'42587',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515651',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-B83B4',inventory_number:'SBS-0036',type:'desktop',assigned_user_id:'80903',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515652',status:'Activo',location:'DIRECCIÓN DE LICITACIONES Y COSTOS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-EBE8A',inventory_number:'SBS-0037',type:'desktop',assigned_user_id:'80026',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515653',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'RH',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-8B832',inventory_number:'SBS-0038',type:'desktop',assigned_user_id:'41968',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:'  GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515654',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-E1886',inventory_number:'SBS-0039',type:'desktop',assigned_user_id:'46813',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515655',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-7195E',inventory_number:'SBS-0040',type:'desktop',assigned_user_id:'26655',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515656',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'VEHICULOS',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-C1F8A',inventory_number:'SBS-0041',type:'desktop',assigned_user_id:'45728',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515657',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'PROGRAMACION',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-7FA24',inventory_number:'SBS-0042',type:'desktop',assigned_user_id:'28118',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515658',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-F5403',inventory_number:'SBS-0043',type:'desktop',assigned_user_id:'45439',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 3 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515659',status:'Activo',location:'DIRECCION DE ATENCION Y GESTION AL CIUDADANO',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-CF566',inventory_number:'SBS-0044',type:'desktop',assigned_user_id:'34449',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515660',status:'Activo',location:'DIRECCIÓN DE LICITACIONES Y COSTOS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-79BC7',inventory_number:'SBS-0045',type:'desktop',assigned_user_id:'47847',brand:'Dell',model:'Inspire',processor:'',ram:'',hard_drive:'',serial_number:'1561515661',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-53E37',inventory_number:'SBS-0046',type:'desktop',assigned_user_id:'80892',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515662',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-F3226',inventory_number:'SBS-0047',type:'desktop',assigned_user_id:'42944',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515663',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-9767C',inventory_number:'SBS-0048',type:'desktop',assigned_user_id:'80889',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 3 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515664',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-F06E8',inventory_number:'SBS-0049',type:'desktop',assigned_user_id:'33549',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515665',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-53D76',inventory_number:'SBS-0050',type:'desktop',assigned_user_id:'46624',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515666',status:'Activo',location:'FAIS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-89A60',inventory_number:'SBS-0051',type:'desktop',assigned_user_id:'33295',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515667',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-B8748',inventory_number:'SBS-0052',type:'desktop',assigned_user_id:'45079',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 8GB de Ram ',hard_drive:' Disco Solido de 240 GB.',serial_number:'1561515668',status:'Activo',location:'SISTEMAS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-1BCFE',inventory_number:'SBS-0053',type:'desktop',assigned_user_id:'43183',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515669',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-BFB75',inventory_number:'SBS-0054',type:'desktop',assigned_user_id:'23950',brand:'Dell',model:'Inspire',processor:' Procesador E4500',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515670',status:'Activo',location:'DIRECCION DE ATENCION Y GESTION AL CIUDADANO',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-ACEE8',inventory_number:'SBS-0055',type:'desktop',assigned_user_id:'33496',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  1TB GB.',serial_number:'1561515671',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5E593',inventory_number:'SBS-0056',type:'desktop',assigned_user_id:'47942',brand:'Dell',model:'Inspire',processor:' Procesador ',ram:'  GB de Ram ',hard_drive:' Disco Solido de   GB.',serial_number:'1561515672',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-84926',inventory_number:'SBS-0057',type:'desktop',assigned_user_id:'46764',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515673',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-BE997',inventory_number:'SBS-0058',type:'desktop',assigned_user_id:'45725',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  1TB GB.',serial_number:'1561515674',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-8EFCE',inventory_number:'SBS-0059',type:'desktop',assigned_user_id:'42622',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515675',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-51172',inventory_number:'SBS-0060',type:'desktop',assigned_user_id:'43908',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515676',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-3D929',inventory_number:'SBS-0061',type:'desktop',assigned_user_id:'48181',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 3 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515677',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-493D8',inventory_number:'SBS-0062',type:'desktop',assigned_user_id:'41969',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Duro de  1TB GB Mecanico.',serial_number:'1561515678',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC99',inventory_number:'SBS-0063',type:'desktop',assigned_user_id:'45488',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515679',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC99',inventory_number:'SBS-0064',type:'desktop',assigned_user_id:'41219',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515680',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-5BC100',inventory_number:'SBS-0065',type:'desktop',assigned_user_id:'41971',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515681',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC101',inventory_number:'SBS-0066',type:'desktop',assigned_user_id:'14621',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515682',status:'Activo',location:'DIRECCIÓN GENERAL DE DESARROLLO REGIONAL',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC102',inventory_number:'SBS-0067',type:'desktop',assigned_user_id:'42951',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515683',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC103',inventory_number:'SBS-0068',type:'desktop',assigned_user_id:'46581',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 2 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515684',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'RH',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-5BC104',inventory_number:'SBS-0069',type:'desktop',assigned_user_id:'38796',brand:'Dell',model:'Inspire',processor:' Procesador E5400 ',ram:' 4 GB de Ram ',hard_drive:' Disco Duro 320 GB HDD.',serial_number:'1561515685',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC105',inventory_number:'SBS-0070',type:'desktop',assigned_user_id:'80887',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 2 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515686',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC106',inventory_number:'SBS-0071',type:'desktop',assigned_user_id:'45247',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  500 GB Mecanico.',serial_number:'1561515687',status:'Activo',location:'FAIS',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC107',inventory_number:'SBS-0072',type:'desktop',assigned_user_id:'46851',brand:'Dell',model:'Inspire',processor:'',ram:'',hard_drive:'',serial_number:'1561515688',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Sin Equipo',created_at:now,updated_at:now},
{id:'EQP-5BC108',inventory_number:'SBS-0073',type:'desktop',assigned_user_id:'80877',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515689',status:'Activo',location:'DIRECCIÓN DE LICITACIONES Y COSTOS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC109',inventory_number:'SBS-0074',type:'desktop',assigned_user_id:'43994',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515690',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC110',inventory_number:'SBS-0075',type:'desktop',assigned_user_id:'41581',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 3 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515691',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'En proceso SSD',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC111',inventory_number:'SBS-0076',type:'desktop',assigned_user_id:'44362',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515692',status:'Activo',location:'DIRECCIÓN DE LICITACIONES Y COSTOS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC112',inventory_number:'SBS-0077',type:'desktop',assigned_user_id:'47945',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 3 GB de Ram ',hard_drive:' Disco Duro de  250 GB Mecanico.',serial_number:'1561515693',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC113',inventory_number:'SBS-0078',type:'desktop',assigned_user_id:'48199',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515694',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC114',inventory_number:'SBS-0079',type:'desktop',assigned_user_id:'48315',brand:'Dell',model:'Inspire',processor:'',ram:'',hard_drive:'',serial_number:'1561515695',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Sin Equipo',created_at:now,updated_at:now},
{id:'EQP-5BC115',inventory_number:'SBS-0080',type:'desktop',assigned_user_id:'48032',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515696',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'PROGRAMACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC116',inventory_number:'SBS-0081',type:'desktop',assigned_user_id:'42651',brand:'Dell',model:'Inspire',processor:' Procesador I5-12400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515697',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC117',inventory_number:'SBS-0082',type:'desktop',assigned_user_id:'48198',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515698',status:'Activo',location:'FAIS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC118',inventory_number:'SBS-0083',type:'desktop',assigned_user_id:'42956',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515699',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC119',inventory_number:'SBS-0084',type:'desktop',assigned_user_id:'41972',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515700',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC120',inventory_number:'SBS-0085',type:'desktop',assigned_user_id:'42954',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515701',status:'Activo',location:'DIRECCION DE ATENCION Y GESTION AL CIUDADANO',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC121',inventory_number:'SBS-0086',type:'desktop',assigned_user_id:'48034',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515702',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC122',inventory_number:'SBS-0087',type:'desktop',assigned_user_id:'45207',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515703',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC123',inventory_number:'SBS-0088',type:'desktop',assigned_user_id:'38473',brand:'Dell',model:'Inspire',processor:' Procesador RYZEN 5 5600',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515704',status:'Activo',location:'FAIS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC124',inventory_number:'SBS-0089',type:'desktop',assigned_user_id:'47752',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515705',status:'Activo',location:'UNIDAD IGUALDAD DE GENERO',description:'administrativo',notes:'Reemplazo Teclado y Mouse',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-5BC125',inventory_number:'SBS-0090',type:'desktop',assigned_user_id:'48180',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515706',status:'Activo',location:'DIRECCION DE ATENCION Y GESTION AL CIUDADANO',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC126',inventory_number:'SBS-0091',type:'desktop',assigned_user_id:'47783',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515707',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-5BC127',inventory_number:'SBS-0092',type:'desktop',assigned_user_id:'46700',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515708',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC128',inventory_number:'SBS-0093',type:'desktop',assigned_user_id:'12802',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515709',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'PROGRAMACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC130',inventory_number:'SBS-0094',type:'desktop',assigned_user_id:'81434',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515711',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC131',inventory_number:'SBS-0095',type:'desktop',assigned_user_id:'82961',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515712',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC132',inventory_number:'SBS-0096',type:'desktop',assigned_user_id:'40979',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515713',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-5BC133',inventory_number:'SBS-0097',type:'desktop',assigned_user_id:'47941',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515714',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC134',inventory_number:'SBS-0098',type:'desktop',assigned_user_id:'48063',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515715',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC135',inventory_number:'SBS-0099',type:'desktop',assigned_user_id:'18564',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515716',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC136',inventory_number:'SBS-0100',type:'desktop',assigned_user_id:'40752',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515717',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-5BC137',inventory_number:'SBS-0101',type:'desktop',assigned_user_id:'48031',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515718',status:'Activo',location:'COMUNICACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC138',inventory_number:'SBS-0102',type:'desktop',assigned_user_id:'81581',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  320 GB Mecanico.',serial_number:'1561515719',status:'Activo',location:'DESPACHO',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC139',inventory_number:'SBS-0103',type:'desktop',assigned_user_id:'28122',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515720',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC140',inventory_number:'SBS-0104',type:'desktop',assigned_user_id:'39962',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515721',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC141',inventory_number:'SBS-0105',type:'desktop',assigned_user_id:'80876',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 2 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515722',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC142',inventory_number:'SBS-0106',type:'desktop',assigned_user_id:'47594',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515723',status:'Activo',location:'SUBSECRETARÍA DE DE INCLUSIÓN SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC143',inventory_number:'SBS-0107',type:'desktop',assigned_user_id:'38205',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515724',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'RH',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC144',inventory_number:'SBS-0108',type:'desktop',assigned_user_id:'28129',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515725',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC145',inventory_number:'SBS-0109',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515726',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC146',inventory_number:'SBS-0110',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515727',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC147',inventory_number:'SBS-0111',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 2 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515728',status:'Activo',location:'OFICIALIA DE PARTES',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC148',inventory_number:'SBS-0112',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-10505',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515729',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Ninguna',created_at:now,updated_at:now},
{id:'EQP-5BC149',inventory_number:'SBS-0113',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515730',status:'Activo',location:'DIRECCIÓN GENERAL DE ADMINISTRACIÓN Y PLANEACIÓN',description:'administrativo',notes:'PROGRAMACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC150',inventory_number:'SBS-0114',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Duro de  1TB Mecanico.',serial_number:'1561515731',status:'Activo',location:'BIENESTAR',description:'Captura',notes:'Asignado a Captura Pecera Planta Alta',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC151',inventory_number:'SBS-0115',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515732',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC152',inventory_number:'SBS-0116',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515733',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC153',inventory_number:'SBS-0117',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-4590',ram:' 4 GB de Ram ',hard_drive:' Disco Duro Solido de 240 GB',serial_number:'1561515734',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-5BC154',inventory_number:'SBS-0118',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5800',ram:' 3 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515735',status:'Activo',location:'UNIDAD IGUALDAD DE GENERO',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-5BC155',inventory_number:'SBS-0119',type:'laptop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6200',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515736',status:'Activo',location:'COMUNICACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Requiere Ram para aumentar capacidad',created_at:now,updated_at:now},
{id:'EQP-5BC156',inventory_number:'SBS-0120',type:'laptop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I7-11800H',ram:' 16 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515737',status:'Activo',location:'COMUNICACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC157',inventory_number:'SBS-0121',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515738',status:'Activo',location:'DIRECCION GENERAL JURIDICA Y DE TRANSPARENCIA',description:'administrativo',notes:'Equipo y Lugar sin Asignar',requirement:'Disco Duro de Estado Solido de 240 GB',created_at:now,updated_at:now},
{id:'EQP-5BC158',inventory_number:'SBS-0122',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5700',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515739',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC159',inventory_number:'SBS-0123',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515740',status:'Activo',location:'SUBSECRETARÍA DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC160',inventory_number:'SBS-0124',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E7300',ram:' 2 GB de Ram ',hard_drive:' Disco Duro de  160 GB Mecanico.',serial_number:'1561515741',status:'Activo',location:'DIRECCION GENERAL DE PARTICIPACION SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Disco Duro de Estado Solido de 240 GB y 4Gb de Ram',created_at:now,updated_at:now},
{id:'EQP-5BC161',inventory_number:'SBS-0125',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  480 GB.',serial_number:'1561515742',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC162',inventory_number:'SBS-0126',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515743',status:'Activo',location:'FAIS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC163',inventory_number:'SBS-0127',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515744',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'PROGRAMACION',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC164',inventory_number:'SBS-0128',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador E5400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515745',status:'Activo',location:'SUBDIRECCIÓN DE EVALUACIÓN SOCIAL ',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC165',inventory_number:'SBS-0129',type:'laptop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:'',ram:'',hard_drive:'',serial_number:'1561515746',status:'Activo',location:'DIRECCIÓN GENERAL DE INFRAESTRUCTURA SOCIAL',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC166',inventory_number:'SBS-0130',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-10400',ram:' 8 GB de Ram ',hard_drive:' Disco Solido de  1TB GB.',serial_number:'1561515747',status:'Activo',location:'SISTEMAS',description:'administrativo',notes:'sin observacion',requirement:'Ninguno',created_at:now,updated_at:now},
{id:'EQP-5BC167',inventory_number:'SBS-0131',type:'desktop',assigned_user_id:'pendiente',brand:'Dell',model:'Inspire',processor:' Procesador I5-6400',ram:' 4 GB de Ram ',hard_drive:' Disco Solido de  240 GB.',serial_number:'1561515748',status:'Activo',location:'DIRECCION GENERAL DE ADMINISTRACION Y PLANEACION',description:'administrativo',notes:'ADMINISTRACION',requirement:'Ninguno',created_at:now,updated_at:now},

        
    ];
    // Mapear y limpiar datos para cumplir con la migración/modelo
    const statusMap = {
      'Activo': 'available',
      'Asignado': 'assigned',
      'Mantenimiento': 'maintenance',
      'Retirado': 'retired'
    };
    const typeMap = {
      'desktop': 'desktop',
      'laptop': 'laptop',
      'printer': 'printer',
      'server': 'server',
      'monitor': 'monitor',
      'other': 'other'
    };
    const equipos = users.map(u => {
      // Generar UUID para id, mapear status y type, limpiar campos y ajustar nombres
      const {
        id, // ignorar el id original
        assigned_user_id, // lo forzamos a null
        status,
        type,
        brand,
        model,
        inventory_number,
        created_at,
        updated_at,
        ...rest
      } = u;
      // Generar un nombre razonable: brand + model, o inventory_number si falta
      let name = '';
      if (brand && model) {
        name = `${brand} ${model}`;
      } else if (brand) {
        name = brand;
      } else if (model) {
        name = model;
      } else {
        name = inventory_number || 'Equipo';
      }
      return {
        id: uuidv4(),
        name,
        ...rest,
        brand,
        model,
        inventory_number,
        type: typeMap[type] || 'other',
        assigned_user_id: null,
        status: statusMap[status] || 'available',
        createdAt: created_at,
        updatedAt: updated_at
      };
    });
    // Agregar Tejaban Principal como área común fija
    equipos.push({
      id: '36b65adf-f5ac-4916-b89f-367598e6ebaa',
      name: 'Tejaban Principal',
      type: 'other',
      brand: 'Área',
      model: 'Común',
      serial_number: 'TP-01',
      inventory_number: '0.00',
      status: 'available',
      location: 'Área Común',
      assigned_user_id: null,
      createdAt: now,
      updatedAt: now
    });
    // await queryInterface.bulkDelete('equipment', null, {});
    await queryInterface.bulkInsert('equipment', equipos, {
      ignoreDuplicates: true
    });
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('equipment', null, {});
  }
};
